baseURL = "https://clojure-conundrums.co.uk/"
languageCode = "en-gb"
title = "Clojure Conundrums"
theme = "vienna"

[Params]
  twitter = "DWMartin41"
  github = "DaveWM"
  reddit = "DaveWM"
  linkedin = "davewm"
  themecolor = "#000000"
  contact = "mailto:mail@davemartin.me"
  subtitle = "Helpful guides for all things Clojure(Script)"
  author = "Dave Martin"
  bio = "Clojure developer at Funding Circle"
  avatar = "/images/profile.jpg"
  description = "A blog about common problems in Clojure/ClojureScript and how to solve them."
